### PR TITLE
chore: migrate to dune, add opam file

### PR DESCRIPTION
**Pull request by c-cube**

### CODE REVIEW

**Comment by astrada** [comment]
Thanks!

**Comment by rgrinberg** [comment]
I believe the readme needs to be updated as well. An opam release would be great too!

**Comment by c-cube** [comment]
Yes, this needs a bit more work (in particular, expose `type t` in main modules, to follow normal conventions).

I was also thinking to functorize over the underlying scheduler and have `rx-lwt` as a library that instantiates the functor over lwt, but maybe that's a bit much.

**Comment by astrada** [comment]
> Yes, this needs a bit more work

Sure! This project was an exercise I started after attending [this course](https://www.mooc-list.com/course/principles-reactive-programming-coursera) to practice a bit the concepts of reactive programming. Notice that I'm not using it for anything serious, so it's not tested. If I remember correctly, it may have some issues with closures that can be collected prematurely by the GC. But if you find some code useful, feel free to reuse it or fork it.

**Pull request merged**
